pre_bump_hooks = [
    "maturin build --release",
    "echo 'bumping from {{latest}} to {{version}}'",
    "cargo set-version {{version}}",
]
post_bump_hooks = []
ignore_merge_commits = true

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]
